In [1]:
# Data Cleaning = the process of fixing / removing incomplete, incorrect, or irrelevant data.
#                 ~75% of work done by pandas is Data Cleaning

In [2]:
import pandas as pd
try:
    df = pd.read_csv('../data.csv')
except Exception as e:
    print(e)

In [3]:
# 1. Drop irrelevant columns

In [4]:
df = df.drop(columns=['No'])
df.head()

         Name  Type1   Type2  Height  Weight  Legendary
0   Bulbasaur  Grass  Poison     0.7     6.9          0
1     Ivysaur  Grass  Poison     1.0     NaN          0
2    Venusaur  Grass  Poison     2.0   100.0          0
3  Charmander   Fire     NaN     NaN     8.5          0
4  Charmeleon   Fire     NaN     1.1    19.0          0

In [5]:
# 2. Handle missing data

In [6]:
pd.set_option('display.max_rows', None) # is used to show all the rows
df = df.dropna(subset=['Name', 'Type1', 'Type2', 'Height', 'Weight'])
df.count()

Name         65
Type1        65
Type2        65
Height       65
Weight       65
Legendary    65
dtype: int64

In [7]:
# df # remove the # to view the entire table

In [8]:
df = df.fillna({'Type2':'None'})
# It will fill the null value with "None"
# But this will not work now as the null values are already removed

In [9]:
# 3. Fix inconsistent values

In [ ]:
df['Type1'] = df['Type1'].replace({'Grass':'GRASS', 'Fire':'FIRE'})
df['Type1'].unique().tolist()

['GRASS',
 'FIRE',
 'Bug',
 'Normal',
 'Poison',
 'Water',
 'Rock',
 'Electric',
 'Ghost',
 'Ground',
 'Psychic',
 'Ice',
 'Dragon']

In [11]:
# 4. Standardize text

In [12]:
df['Name'] = df['Name'].str.lower()
df['Name'].head()

0      bulbasaur
2       venusaur
5      charizard
11    butterfree
13        kakuna
Name: Name, dtype: object

In [13]:
# 5. Fix Data Types

In [14]:
# Change the data-type of Legendary to Boolean

df['Legendary'] = df['Legendary'].astype(bool)
df

           Name     Type1     Type2  Height  Weight  Legendary
0     bulbasaur     GRASS    Poison     0.7     6.9      False
2      venusaur     GRASS    Poison     2.0   100.0      False
5     charizard      FIRE    Flying     1.7    90.5      False
11   butterfree       Bug    Flying     1.1    32.0      False
13       kakuna       Bug    Poison     0.6    10.0      False
14     beedrill       Bug    Poison     1.0    29.5      False
15       pidgey    Normal    Flying     0.3    -1.8      False
16    pidgeotto    Normal    Flying     1.1    30.0      False
17      pidgeot    Normal    Flying     1.5    39.5      False
20      spearow    Normal    Flying     0.3     2.0      False
21       fearow    Normal    Flying     1.2    38.0      False
30    nidoqueen    Poison    Ground     1.3    60.0      False
33     nidoking    Poison    Ground     1.4    62.0      False
38   jigglypuff    Normal     Fairy     0.5     5.5      False
39   wigglytuff    Normal     Fairy     1.0    12.0      False
40        zubat    Poison    Flying     0.8     7.5      False
41       golbat    Poison    Flying     1.6    55.0      False
42       oddish     GRASS    Poison     0.5     5.4      False
43        gloom     GRASS    Poison     0.8     8.6      False
44    vileplume     GRASS    Poison     1.2    18.6      False
45        paras       Bug     Grass     0.3     5.4      False
46     parasect       Bug     Grass     1.0    29.5      False
47      venonat       Bug    Poison     1.0    30.0      False
48     venomoth       Bug    Poison     1.5    12.5      False
61    poliwrath     Water  Fighting     1.3    54.0      False
68   bellsprout     GRASS    Poison     0.7     4.0      False
69   weepinbell     GRASS    Poison     1.0     6.4      False
70   victreebel     GRASS    Poison     1.7    15.5      False
71    tentacool     Water    Poison     0.9    45.5      False
72   tentacruel     Water    Poison     1.6    55.0      False
73      geodude      Rock    Ground     0.4    20.0      False
74     graveler      Rock    Ground     1.0   105.0      False
75        golem      Rock    Ground     1.4   300.0      False
78     slowpoke     Water   Psychic     1.2    36.0      False
79      slowbro     Water   Psychic     1.6    78.5      False
80    magnemite  Electric     Steel     0.3     6.0      False
81     magneton  Electric     Steel     1.0    60.0      False
82   farfetch'd    Normal    Flying     0.8    15.0      False
83        doduo    Normal    Flying     1.4    39.2      False
84       dodrio    Normal    Flying     1.8    85.2      False
86      dewgong     Water       Ice     1.7   120.0      False
90     cloyster     Water       Ice     1.5   132.5      False
91       gastly     Ghost    Poison     1.3     0.1      False
92      haunter     Ghost    Poison     1.6     0.1      False
93       gengar     Ghost    Poison     1.5    40.5      False
94         onix      Rock    Ground     8.8   210.0      False
101   exeggcute     GRASS   Psychic     0.4     2.5      False
102   exeggutor     GRASS   Psychic     2.0   120.0      False
110     rhyhorn    Ground      Rock     1.0   115.0      False
111      rhydon    Ground      Rock     1.9   120.0      False
120     starmie     Water   Psychic     1.1    80.0      False
121    mr. mime   Psychic     Fairy     1.3    54.5      False
122     scyther       Bug    Flying     1.5    56.0      False
123        jynx       Ice   Psychic     1.4    40.6      False
129    gyarados     Water    Flying     6.5   235.0      False
130      lapras     Water       Ice     2.5   220.0      False
137     omanyte      Rock     Water     0.4     7.5      False
138     omastar      Rock     Water     1.0    35.0      False
139      kabuto      Rock     Water     0.5    11.5      False
140    kabutops      Rock     Water     1.3    40.5      False
141  aerodactyl      Rock    Flying     1.8    59.0      False
143    articuno       Ice    Flying     1.7    55.4       True
144      zapdos  Electric    Flying     1.6    52.6       True
145     moltres      FIRE    Flying     2.0    60.0       True
148   dragonite    Dragon    Flying     2.2   210.0      False